import numpy as np
from scipy.integrate import solve_bvp
from ctr_sim.robot import ConcentricTubeRobot


def theta_index(i: int) -> int:
    """Index of θᵢ in the state vector."""
    return 2 * i

def theta_dot_index(i: int) -> int:
    """Index of dθᵢ/ds in the state vector."""
    return 2 * i + 1


def torsion_ode_scalar(
    s: float,
    y: np.ndarray,
    robot: ConcentricTubeRobot,
) -> np.ndarray:
    """
    Compute the torsion ODE for the CTR.

    Parameters
    ----------
    s : float
        Arc length.

    y : np.ndarray
        State vector:
        y = [
            θ₁,
            θ₁',
            θ₂,
            θ₂',
            ...
            θₙ,
            θₙ'
        ]

    robot : ConcentricTubeRobot
        Robot model.

    Returns
    -------
    np.ndarray
        State derivative dy/ds.
    """

    n = len(robot.tubes)
    dyds = np.zeros_like(y)

    for i in range(n):

        theta_i = y[theta_index(i)]
        theta_dot_i = y[theta_dot_index(i)]

        tube_i = robot.tubes[i]
        beta_i = robot.state.insertions[i]

        if s > beta_i:

            dyds[theta_index(i)] = 0.0
            dyds[theta_dot_index(i)] = 0.0

            continue

        dyds[theta_index(i)] = theta_dot_i

        # Sum the torsional interaction moments generated by every
        # other tube 'j' that is present at the current arc length on tube 'i'.
        moment = 0.0

        kappa_i = tube_i.precurvature

        for j in range(n):

            if j == i:
                continue

            tube_j = robot.tubes[j]
            beta_j = robot.state.insertions[j]

            if s > beta_j:
                continue

            theta_j = y[theta_index(j)]

            kappa_j = tube_j.precurvature

            moment += (
                tube_j.EI
                * kappa_i
                * kappa_j
                * np.sin(theta_i - theta_j)
            )

        dyds[theta_dot_index(i)] = moment / tube_i.GJ

    return dyds
    
def torsion_ode(
    s: np.ndarray,
    y: np.ndarray,
    robot: ConcentricTubeRobot,
) -> np.ndarray:
    """
    Vectorized wrapper for the scalar torsion ODE.

    This function adapts the scalar ODE implementation to the interface
    expected by scipy.integrate.solve_bvp().
    """

    dyds = np.zeros_like(y)

    for k in range(len(s)):

        dyds[:, k] = torsion_ode_scalar(
            s[k],
            y[:, k],
            robot,
        )

    return dyds


def torsion_boundary_conditions(
    ya: np.ndarray,
    yb: np.ndarray,
    robot: ConcentricTubeRobot,
) -> np.ndarray:
    """
    Boundary conditions for the torsion BVP.

    Parameters
    ----------
    ya : np.ndarray
        State at s = 0.

    yb : np.ndarray
        State at the distal end of the robot.

    robot : ConcentricTubeRobot

    Returns
    -------
    np.ndarray
        Boundary condition residual vector.
    """

    n = len(robot.tubes)
    residual = np.zeros(2 * n)

    for i in range(n):

        alpha_i = robot.state.rotations[i]

        # Base boundary condition:
        # θᵢ(0) = αᵢ
        residual[theta_index(i)] = (
            ya[theta_index(i)] - alpha_i
        )

        # Distal boundary condition:
        # dθᵢ/ds = 0
        residual[theta_dot_index(i)] = (
            yb[theta_dot_index(i)]
        )
    
    return residual



def construct_initial_guess(
    robot: ConcentricTubeRobot,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Construct an initial guess for the torsion BVP.

    The initial guess assumes that each tube maintains its base rotation
    (αᵢ) along its entire inserted length and experiences zero twist.

    Returns
    -------
    s : np.ndarray
        Arc-length sampling locations.

    initial_guess : np.ndarray
        Initial state guess for solve_bvp().
    """

    n = len(robot.tubes)

    # The BVP is solved over the entire inserted robot length.
    L_total = max(robot.state.insertions)

    # Initial arc-length sampling.
    s = np.linspace(0.0, L_total, 50)

    # Initial guess for the state vector:
    #
    # y =
    # [θ₁
    #  θ₁'
    #  θ₂
    #  θ₂'
    #   ⋮
    #  θₙ
    #  θₙ']
    #
    initial_guess = np.zeros((2 * n, len(s)))

    for i in range(n):

        alpha_i = robot.state.rotations[i]

        # Assume each tube initially maintains its base rotation.
        initial_guess[theta_index(i), :] = alpha_i

        # Assume zero torsional strain everywhere.
        initial_guess[theta_dot_index(i), :] = 0.0

    return s, initial_guess



def solve_torsion_bvp(
    robot: ConcentricTubeRobot,
):
    """
    Solve the torsion boundary value problem.

    This function solves for the tube torsion angles θ(s) that satisfy
    the equilibrium equations and boundary conditions for the current
    robot configuration.

    Parameters
    ----------
    robot : ConcentricTubeRobot
        Robot containing the tube properties and current configuration
        (α, β).

    Returns
    -------
    object
        SciPy boundary value problem solution object.

    Notes
    -----
    This function returns the raw SciPy solution. The solution can be
    evaluated at arbitrary arc-length locations using

        bvp_solution.sol(s)

    The evaluated torsion angles are later incorporated into the
    CTRSolution object by the top-level forward mechanics solver.
    """

    s, initial_guess = construct_initial_guess(robot)

    bvp_solution = solve_bvp(
        lambda s, y: torsion_ode(s, y, robot),
        lambda ya, yb: torsion_boundary_conditions(ya, yb, robot),
        s,
        initial_guess,
    )
    return bvp_solution

def evaluate_torsion_solution(
    bvp_solution,
    s: np.ndarray,
) -> np.ndarray:
    """
    Evaluate the torsion solution at arbitrary arc-length locations.
    """

    y = bvp_solution.sol(s)

    return y[0::2, :]

    